### ISSUE TITLE
ImportError: cannot import name 'Specifier' from 'packaging.requirements'

### ISSUE THREAD

**Issue by Luca2352** [PyMoDAQ/PyMoDAQ#112]
Hello
while searching for an open source software for data acquisition, I came across your software. Unfortunately, I get the following error message after running it. I have followed all installation steps from the documentation. The error occurs on a Windows 11 and Linux system.

Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\pymodaq\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\miniconda3\envs\pymodaq\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\miniconda3\envs\pymodaq\Scripts\dashboard.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\miniconda3\envs\pymodaq\lib\site-packages\pymodaq\dashboard.py", line 38, in <module>
    from pymodaq_plugin_manager.manager import PluginManager
  File "C:\Users\user\miniconda3\envs\pymodaq\lib\site-packages\pymodaq_plugin_manager\manager.py", line 13, in <module>
    from pymodaq_plugin_manager.validate import validate_json_plugin_list, get_plugins, get_plugin, get_check_repo,\
  File "C:\Users\user\miniconda3\envs\pymodaq\lib\site-packages\pymodaq_plugin_manager\validate.py", line 7, in <module>
    from packaging.requirements import Requirement, SpecifierSet, Specifier
ImportError: cannot import name 'Specifier' from 'packaging.requirements' (C:\Users\user\miniconda3\envs\pymodaq\lib\site-packages\packaging\requirements.py)

Would be happy if you could help me.

**Comment by aurore-finco** [comment]
Hi! 
This seems to be an issue with the package packaging. I had a quick look, I think that Specifier and SpecifierSet should be imported from packaging.specifiers rather than packaging.requirements.

**Comment by seb5g** [comment]
This is indeed related to import from this package. Basically now that pymodaq V4 is out, the manager is checking if the plugins are compatible or not with the installed pymodaq version 3.X or 4.X. On my version of packaging (21) this import was working! I'll patch this. In the mean time, you can manually install the pymodaq_plugin_manager version 0.0.18

**Comment by seb5g** [comment]
I had some time so patched it see: 

https://github.com/PyMoDAQ/pymodaq_plugin_manager/pull/13

which collided with Aurore's patch (sorry...). I'll create a release from this so it will be available on pypi soon
