### ISSUE TITLE
PI extension with PyMoDAQ4

### ISSUE THREAD

**Issue by jerlfan** [PyMoDAQ/PyMoDAQ#116]
We are using a PID extensions with pymodaq 4. The model is intialized properly, but when intializing the PID we get the following errors

Traceback (most recent call last):
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\extensions\pid\pid_controller.py", line 161, in process_output
    self.output_viewer.show_data([[dat] for dat in datas['output']])
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\utils\plotting\data_viewers\viewer.py", line 318, in show_data
    if len(data.shape) > 4:
AttributeError: 'list' object has no attribute 'shape'

It is related to the modification of the dat structures in pymodaq 4.

**Comment by jerlfan** [comment]
In pymodaq.extensions.pid.pid_controller 

we have replaced the line 160:

self.output_viewer.show_data([[dat] for dat in datas['output']])

by 
data=DataRaw(name='pid output'
data=datas['output']) self.output_viewer.show_data(data)

We got the following errors: 
Traceback (most recent call last):
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\extensions\pid\pid_controller.py", line 162, in process_output
    data=DataRaw(name='pid output',data=datas['output'])
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\utils\data.py", line 1484, in __init__
    super().__init__(*args, source=DataSource['raw'], **kwargs)
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\utils\data.py", line 1179, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\utils\data.py", line 490, in __init__
    self.data = data  # dim consistency is actually checked within the setter method
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\utils\data.py", line 748, in data
    data = self._check_data_type(data)
  File "C:\Users\manip-lumi\Documents\GitHub\PyMoDAQ2\src\pymodaq\utils\data.py", line 702, in _check_data_type
    raise TypeError(f'Data should be an non-empty list of non-empty numpy arrays')
TypeError: Data should be an non-empty list of non-empty numpy arrays

**Comment by quantumm** [comment]
Hi Jérémie,
For now the PID extension in not compatible with the v4.
I would recommand that you keep the v3 for now.
It is planned to make it compatible but difficult to fix the date of the release.
I will keep you updated!

**Comment by seb5g** [comment]
the new pull request #148 should solve this issue!

**Comment by seb5g** [comment]
Could either Jérémie or Quantuum try this and let us know if it is working properly now?

**Comment by seb5g** [comment]
PID extension is working well!
