### ISSUE TITLE
Mac compatibility: dashboard

### ISSUE THREAD

**Issue by Atmos-sp3re** [PyMoDAQ/PyMoDAQ#153]
I am using Mac OS with Python 3.10 and PYMODAQ v4.0.. I have no problem during the installation of the various modules. However, when I launch the dashboard, I encounter this error. I suppose the the issue is due to mac os

```
(pymo4_py310) jh@capsule ~ % dashboard
Traceback (most recent call last):
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('Library/Application Support/.pymodaq')
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jh/anaconda3/envs/pymo4_py310/bin/dashboard", line 5, in <module>
    from pymodaq.dashboard import main
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pymodaq/dashboard.py", line 37, in <module>
    from pymodaq_plugin_manager.manager import PluginManager
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pymodaq_plugin_manager/manager.py", line 13, in <module>
    from pymodaq_plugin_manager.validate import get_plugins
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pymodaq_plugin_manager/validate.py", line 9, in <module>
    import pkg_resources
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 622, in _build_master
    ws = cls()
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 615, in __init__
    self.add_entry(entry)
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 671, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2075, in find_distributions
    importer = get_importer(path_item)
  File "/Users/jh/anaconda3/envs/pymo4_py310/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'

```

**Comment by Atmos-sp3re** [comment]
Issue is solved by installing python 3.9.
