### ISSUE TITLE
How to handle multiaxes controllers with a priori unknown number of axes

### ISSUE THREAD

**Issue by rgeneaux** [PyMoDAQ/PyMoDAQ#188]
Hi,
There is a question I've ran into when writing several actuators plugins, and i'd like to know if someone has an opinion. 
For a multiaxis controller, we now define something like (cf [doc](http://pymodaq.cnrs.fr/en/pymodaq-dev/developer_folder/instrument_plugins.html#actuator-plugin-having-multiple-axis))
`_axis_names = {'Xaxis': 0, 'Yaxis': 1, 'Zaxis': 2}`

However, my issue is that some controllers can handle an arbitrary number of axes - some just daisy chain each other and could potentially have dozens of axes, but we can't know that before initializing the self.controller.

The initialization procedure goes something like
- when importing the plugin, run some API method to search for the connected controllers, generate a list and put that into the parameter tree
- the user chooses which controller to use in the list, then clicks initialize
- the controller uses an API method that lists all available axes. We can then populate `_axis_names` with those axes and the user can swap.
This is fine 

The issue arises when using a preset: ideally we'd like a preset to launch and directly initialize the controller with a chosen axis. However there is no way to define a preset in this way, since the `_axis_names` has not been populated yet when we create the preset (presets are defined before initializing the controller).

We've hacked our way around this in two ways for different plugins, 

1. you can choose that this type of controller will have a fixed number of axes and write `_axis_names = {'Axis 1': 0, 'Axis 2': 1, 'Axis 3': 2}` at the top of the plugin, then update the names once the controller knows them (this is SmaractMCS2). 

2. Another thing I did was to redefine self.settings['multiaxes', 'axis'], instead of a dictionnary it becomes an integer and the user can just use whatever index they want in the preset, and the controller will try to initialize this index (this is Zaber). It writes the names of the axes into another field of the tree once it is available. 

Neither solutions are user friendly: when defining the preset, we have to remember which axes are what (they don't have their names yet). Second solution at least has the advantage of handling arbitrary number of axes.

So I guess we need to find some standardized way of doing that! Thoughts?

**Comment by seb5g** [comment]
To add some thoughts (as requested ;-) ), have you noticed in the preset the little "**plus**"" button on the right part of the combo widget? Well if you press it it will allow you to add entries into the combo:

![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/afd8f769-86b8-46d2-a659-cdb8719cb146)

so far it was only working with list type of combo, but now that we have introduced the dict type, i added the feature that you have to first enter a string then an integer (key, value) new pair in the dict. I just did a PR on that: #189 

It means that if you know the "value" of your axis you can preset it in the Preset! (Don't need anymore to switch to integer widget). So this goes together with your point *2*

**Comment by rgeneaux** [comment]
ah, wunderbar!! 
I'll try to use dicts in the Zaber plugin and test if I can do the preset like before.

**Comment by seb5g** [comment]
can we close this issue @rgeneaux ?

**Comment by rgeneaux** [comment]
Yes
@seb5g will you merge the settings branch into pymodaq-dev?

**Comment by seb5g** [comment]
> Yes @seb5g will you merge the settings branch into pymodaq-dev?

@rgeneaux I'm waiting for @Ashwolaa to make changes to its PR #205 before merging it, then I'll merge the settings branch

**Comment by rgeneaux** [comment]
Hi, I am reopening this because I think this doesn't work anymore with the introduction of units!
The case is the following:
- We have a move controller with possibly many axes connected
- The plugin class (smaract in my case) only declares three axes by default `axis_names= {'CH1': 0, 'CH2': 1, 'CH3': 2}`
- Upon ini_stage, we check if there are more axes available and update the list of available axis, the user can then change to CH10 or something.
This part is fine! 

the problem is again when defining a preset, which you solved last time by using that + button:

<img width="823" height="326" alt="Image" src="https://github.com/user-attachments/assets/96d2d913-ee97-4c93-a080-8072c173c305" />

we can use to add the str "CH10", and the corresponding integer.

But now, when the preset is launched, daq_move checks for units and epsilons for the chosen axis, which.. is not defined yet since the controller is not initialized

```

2025-10-03 10:49:14,489 - pymodaq.pymodaq.daq_move.Probe Wedge.actuator - ERROR - 'CH10'
Traceback (most recent call last):
  File "C:\Users\ATTOExpFa1b\AppData\Local\miniforge3\envs\v5\lib\site-packages\pymodaq\control_modules\daq_move.py", line 789, in ini_stage
    self.hardware = class_(self, params_state)
  File "C:\Users\ATTOExpFa1b\AppData\Local\miniforge3\envs\v5\lib\site-packages\pymodaq\control_modules\move_utility_classes.py", line 314, in __init__
    self.axis_name = self.axis_name  # to trigger some actions on units and epsilons
  File "C:\Users\ATTOExpFa1b\AppData\Local\miniforge3\envs\v5\lib\site-packages\pymodaq\control_modules\move_utility_classes.py", line 449, in axis_name
    self.axis_unit = self.axis_unit
  File "C:\Users\ATTOExpFa1b\AppData\Local\miniforge3\envs\v5\lib\site-packages\pymodaq\control_modules\move_utility_classes.py", line 338, in axis_unit
    return self.axis_units[self.axis_index_key]
KeyError: 'CH10'

```
I don't know how to proceed! the temporary solution is to add " {'CHN': N}" for N=1..20 to the axis_name dictionnary, which is not great
thanks

**Comment by Ashwolaa** [comment]
I guess, it is really about making sure that units is never required during the whole process and fallbacks onto a default value of None / ""
This would simplifies a lot the syntax and avoid these errors.
