### ISSUE TITLE
Could not launch any teaching example

### ISSUE THREAD

**Issue by ArthurMarguerite** [PyMoDAQ/PyMoDAQ#190]
Hello,

I tried to reproduce the teaching examples on a different computer (Windows10). Even with the correction it returns errors, both on main branch and pymodaq-dev branch.

I have:
python = 3.10
pyqt5 = 5.15.10
pymodaq = 4.0.8

Example : when trying to launch `daq_1Dviewer_Spectrometer.py`
```
Traceback (most recent call last):
  File "XXX\PyMoDaq\PyMoDAQ_dev_arthur\pymodaq_plugins_teaching\src\pymodaq_plugins_teaching\daq_viewer_plugins\plugins_1D\daq_1Dviewer_Spectrometer.py", line 116, in <module>
    main(__file__)

  File "XXX\PyMoDaq\PyMoDAQ_dev_arthur\PyMoDAQ\src\pymodaq\control_modules\viewer_utility_classes.py", line 116, in main
    prog.detector = detector

  File "XXX\PyMoDaq\PyMoDAQ_dev_arthur\PyMoDAQ\src\pymodaq\control_modules\daq_viewer.py", line 308, in detector
    raise ValueError(f'{det} is not a valid Detector: {self.detectors}')
ValueError: Spectrometer is not a valid Detector: ['Mock', 'Mock_spectro', 'TCPServer']
```

`daq_move_Monochromator.py` returns:
```
Traceback (most recent call last):
  File "XXX\PyMoDaq\PyMoDAQ_dev_arthur\pymodaq_plugins_teaching\src\pymodaq_plugins_teaching\daq_move_plugins\daq_move_Monochromator.py", line 167, in <module>    main(__file__)

  File "XXX\PyMoDaq\PyMoDAQ_dev_arthur\PyMoDAQ\src\pymodaq\control_modules\move_utility_classes.py", line 149, in main
    prog.actuator = Path(plugin_file).stem[9:]

  File "XXX\PyMoDaq\PyMoDAQ_dev_arthur\PyMoDAQ\src\pymodaq\control_modules\daq_move.py", line 555, in actuator
    raise ActuatorError(f'{act_type} is an invalid actuator, should be within {ACTUATOR_TYPES}')
pymodaq.utils.exceptions.ActuatorError: Monochromator is an invalid actuator, should be within ['Mock', 'MockCamera', 'MockNamedAxes', 'MockTau', 'MockTauMulti', 'TCPServer']
```

**Comment by seb5g** [comment]
You probably didn't install the package yet so python cannot see the plugin?!

**Comment by ArthurMarguerite** [comment]
Indeed. Rookie mistake here.
