### ISSUE TITLE
Having trouble with ViewerND

### ISSUE THREAD

**Issue by rgeneaux** [PyMoDAQ/PyMoDAQ#297]
Hello,

I am having trouble using the ViewerND, which probably means I don't fully understand the navigator axis principle (even though I was paying attention at the last user meeting!!). I checked the MockND example as suggested by @Ashwolaa but I still can't figure it out.

I have a camera sending a sequence of 2D frames, which is shaped into a 3D np array called "data" below. So the navigation axis is the along the frame number, and the signal axes are X and Y.

Then the emit_data goes
```
        self.x_axis = Axis(data=np.linspace(0, frame_size_x, frame_size_x, endpoint=False), label='Pixels', index=1)
        self.y_axis = Axis(data=np.linspace(0, frame_size_y, frame_size_y, endpoint=False), label='Pixels', index=0)

        dfp_list = [DataFromPlugins(name='Camera', data=[data],
                          dim='DataND', labels=['Camera image'],
                          nav_indexes=(0,),
                          axis=[Axis(data=np.linspace(0, nframes, nframes, endpoint=False), label='NFrames', index=2), self.x_axis, self.y_axis, ])]

       self.dte_signal.emit(DataToExport('Image sequence', data=dfp_list))

```

But this triggers the following error
```
2024-04-08 17:41:00,606 - pymodaq.viewerND - ERROR - tuple index out of range
Traceback (most recent call last):
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\plotting\data_viewers\viewerND.py", line 224, in update_viewer_data
    data: DataCalculated = self._data.inav[ind_x]
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\slicing.py", line 21, in __getitem__
    return self.obj._slicer(slices, self.is_navigation)
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\data.py", line 1725, in _slicer
    data = DataWithAxes(self.name, data=new_arrays_data, nav_indexes=tuple(nav_indexes), axes=axes,
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\data.py", line 1439, in __init__
    self.set_axes_manager(self.shape, axes=axes, nav_indexes=nav_indexes, **other_kwargs)
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\data.py", line 1450, in set_axes_manager
    self.axes_manager = AxesManagerUniform(data_shape=data_shape, axes=axes, nav_indexes=nav_indexes,
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\data.py", line 1114, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\data.py", line 878, in __init__
    self._check_axis(self._axes)
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\data.py", line 1141, in _check_axis
    if self.get_shape_from_index(axis.index) != axis.size:
  File "C:\Miniconda3\envs\exp4\lib\site-packages\pymodaq\utils\data.py", line 1129, in get_shape_from_index
    return self._data_shape[index]
IndexError: tuple index out of range
```  

What is it that I am doing wrong?
Thanks !

**Comment by seb5g** [comment]
You have to specify all axes in the axes attribute (not the axis attribute). And if the frame axis (with index 2) is the navigation axis then the nav_indexes tuple should be (2, ).

Test this and let us know

**Comment by seb5g** [comment]
how is it?

**Comment by rgeneaux** [comment]
I don't have access to the detector anymore so I wasn't able to test it, but it looks like you caught the issue. I'll close the issue and reopen if I run into issues again! 
thanks
