### ISSUE TITLE
pyqtgraph issue with dashboard new_preset

### ISSUE THREAD

**Issue by seb5g** [PyMoDAQ/PyMoDAQ#315]
as of pyqtgraph version 0.13.4, creating a new preset in the dashboard is inducing an error in the parameter manager:
```
  File "C:\miniforge3\envs\pymo4_teaching\lib\site-packages\pyqtgraph\parametertree\Parameter.py", line 785, in child
    param = self.names[names[0]]
KeyError: 'params'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\weber\Labo\Programmes Python\PyMoDAQ_Git\pymodaq\src\pymodaq\utils\managers\preset_manager.py", line 122, in parameter_tree_changed
    data[0].child('params', 'main_settings', 'module_name').setValue(data[0].child('name').value())
  File "C:\miniforge3\envs\pymo4_teaching\lib\site-packages\pyqtgraph\parametertree\Parameter.py", line 787, in child
KeyError: 'Parameter threshold has no child named params'
```

such an error is not triggered with pyqtgraph < 0.13.4

**Comment by seb5g** [comment]
it seems that pg>0.13.3 is firing the `parameter_tree_changed` slot at new preset creation with a `'childAdded'` change while for pg <=0.13.3 this thing is not fired??
