### ISSUE TITLE
Update of bayesian-optimization module breaks bayesan extension

### ISSUE THREAD

**Issue by louisld** [PyMoDAQ/PyMoDAQ#409]
Yesterday release of `bayesian-optimization` module version `2.0.0` broke the bayesian module of PyMoDAQ because the `UtilityFunction` class was replaced by `AcquisitionFunction`.

https://github.com/bayesian-optimization/BayesianOptimization/pull/447

Running `dashboard` with `bayesian-optimization=2.0.0` raise the following error:
```
Traceback (most recent call last):
  File "/home/louisld/Documents/PyMoDAQ/env/bin/dashboard", line 5, in <module>
    from pymodaq.dashboard import main
  File "/home/louisld/Documents/PyMoDAQ/env/lib/python3.11/site-packages/pymodaq/dashboard.py", line 28, in <module>
    from pymodaq.utils.managers.preset_manager import PresetManager
  File "/home/louisld/Documents/PyMoDAQ/env/lib/python3.11/site-packages/pymodaq/utils/managers/preset_manager.py", line 1, in <module>
    from pymodaq.extensions import get_models
  File "/home/louisld/Documents/PyMoDAQ/env/lib/python3.11/site-packages/pymodaq/extensions/__init__.py", line 16, in <module>
    from .bayesian.bayesian_optimisation import BayesianOptimisation
  File "/home/louisld/Documents/PyMoDAQ/env/lib/python3.11/site-packages/pymodaq/extensions/bayesian/__init__.py", line 1, in <module>
    from . import bayesian_optimisation
  File "/home/louisld/Documents/PyMoDAQ/env/lib/python3.11/site-packages/pymodaq/extensions/bayesian/bayesian_optimisation.py", line 13, in <module>
    from pymodaq.extensions.bayesian.utils import (get_bayesian_models, BayesianModelGeneric,
  File "/home/louisld/Documents/PyMoDAQ/env/lib/python3.11/site-packages/pymodaq/extensions/bayesian/utils.py", line 19, in <module>
    from bayes_opt import UtilityFunction
ImportError: cannot import name 'UtilityFunction' from 'bayes_opt' (/home/louisld/Documents/PyMoDAQ/env/lib/python3.11/site-packages/bayes_opt/__init__.py)
```

An easy workaround is to install version `1.5.1` of the library : `pip install bayesian-optimization==1.5.1`.

**Comment by seb5g** [comment]
I applied the workaround by restricting the version of Bayesian Optimisation package. Will have to work to make it compatible again in its new major!

**Comment by loicguilmard** [comment]
i encoutered this issue. May be i didn't generate my env the right way.
Where did you add this requierement ?

**Comment by seb5g** [comment]
i modified only v5. I'm doing it for v4 right away

**Comment by bernhardlang** [comment]
I ran into that today as well. On a fresh installation of pymodaq (4.4.6), the dashboard won't start. The solution to manually install bayesian-optimization version 1.5.1 still solves the problem.

**Comment by seb5g** [comment]
it seems the last two released were not published on pypi hence the issue you ran into...

**Comment by seb5g** [comment]
I manually triggered the release of version 4.4.7 on pypi. Could you check if it is ok now?

**Comment by loicguilmard** [comment]
prompt# conda create -n pymodaq447test_baye python=3.11
prompt# conda activate pymodaq447test_baye
prompt# pip install pyqt5 pymodaq==4.4.7
...
Collecting bayesian-optimization<2.0.0 (from pymodaq==4.4.7)
  Using cached bayesian_optimization-1.5.1-py3-none-any.whl.metadata (16 kB)
...
prompt# dashboard 
OK !
