### ISSUE TITLE
Cannot initialize any daq_move

### ISSUE THREAD

**Issue by martinluttmann** [PyMoDAQ/PyMoDAQ#458]
Dear all,

Since recently I can't initialize any daq_move module. When I launch a daq_move and click "Initialization", the following appears in the log file, while the led indicator remains red.

> pymodaq.pymodaq.daq_move.test.actuator - ERROR - 'limits' . 
> Traceback (most recent call last):
>   File "...\AppData\Local\miniconda3\envs\pymo_env_exp\Lib\site-packages\pymodaq\control_modules\daq_move.py", line 757, in ini_stage 
> self.hardware = class_(self, params_state)
>                     
>   File "...\AppData\Local\miniconda3\envs\pymo_env_exp\Lib\site-packages\pymodaq_plugins_zaber\daq_move_plugins\daq_move_Zaber.py", line 45, in __init__
>     super().__init__(parent, params_state)
>   File "...\AppData\Local\miniconda3\envs\pymo_env_exp\Lib\site-packages\pymodaq\control_modules\move_utility_classes.py", line 300, in __init__
>     self.axis_units = self._controller_units
>   
>   File "...\AppData\Local\miniconda3\envs\pymo_env_exp\Lib\site-packages\pymodaq\control_modules\move_utility_classes.py", line 347, in axis_units
>     if isinstance(self.axis_names, list):
>                  
>   File "...\AppData\Local\miniconda3\envs\pymo_env_exp\Lib\site-packages\pymodaq\control_modules\move_utility_classes.py", line 452, in axis_names
>     return self.settings.child('multiaxes', 'axis').opts['limits']
> KeyError: 'limits'

Apparently the "bounds" (limits) parameters may be causing the issue.

I first observed this problem with the Zaber plugin (which had been working fine so far), but then I realized I could not control any actuator. Creating a new environment with pymodaq installed, I could at least initialize a "Mock" daq_move, but the real modules are still unusable.

Would anyone have a similar problem, and have any idea of what may be going on here?

Thank you :)

Martin

**Comment by seb5g** [comment]
Hello,
Which version of pymodaq are you running on? We've been working quite a lot on the axis and their units

**Comment by seb5g** [comment]
maybe you've installed from a cached version? The one you should use is pymodaq 4.4.7 that handles properly those axes and their units!

What is weird is you're saying you didn't do anything and suddendly it stoped running. Could you be more explicit?

**Comment by Maloherve** [comment]
Hello, 
I am a colleague of Martin and was the one to get the problem, I can give you more info.

The problem appeared after a "long" (~45 min) scan using this Zaber plugin, and a daq card (who still works well), working with an older version of PyModAq. Close to the end of the scan (~40min), the software crashed. I didn't touch it for the week end and when I came back this week the daq_moves were not working.
Since then I updated to 4.4.7, but the problem still persists.

Like Martin said, creating a new environment allowed to get the mock daq_moves to work, but the Zaber stage still fails to initialize.

Quick note : The software for the stage still works and is able to control the device, so the connection does not seem to be a problem.

Edit : A "home-made" plugin for a Thorlabs stage works in this new environment. So the problem may be from the Zaber plugin.

**Comment by martinluttmann** [comment]
Salut Seb,

As Malo said above, I reinstalled everything (new environment, etc.) , and now I can initialize my homemade daq_move plugins. But for some reason, the Zaber plugin is still not working.. So it seems that the problem is now reduced to the Zaber plugin.

Looking in the plugin daq_move_Zaber.py, you find that the parameter "limits" has been removed to avoid a bug : 

> del params[index]['children'][index2]['limits']     # need to remove limits to avoid bug

Could this be linked to our problem?

What I don't understand is that we did not change anything to our setup, so I don't see why a bug should appear now.

A+

**Comment by seb5g** [comment]
Is the stage still working with it's manufacturer software? Do you have
other actuators to test?

**Comment by Maloherve** [comment]
The stage is still working on the manufacturer software. We don't have other Zaber actuators to test, but our Thorlabs stage still works.

**Comment by rgeneaux** [comment]
Hi guys, 
I've seen this error message a few times since the move plugin template was reworked with new types for axes and all the units stuff. I haven't tested the Zaber plugin since those changes, it might not be compatible.

Can I suggest you try to run on pymodaq==4.2.5? (before these changes were made) I hope this temporarily fixes the error, or at least modifies it.
I'll also go check in our lab which version of the plugin+pymodaq we are running.

**Comment by seb5g** [comment]
@rgeneaux could you pinpoint where the error comes from and we'll make sure to implement something to keep it running. It is good to update plugins but better if they could be compatible for a long time!

**Comment by rgeneaux** [comment]
OK, @Maloherve @martinluttmann I checked on my lab computer:
Last release of Zaber plugin is pymodaq_plugins_zaber==2.0.1

I confirm that it works on pymodaq==4.2.5, but on pymodaq==4.4.7, I get the same error as you. So this is coming from the plugin that is not compatible anymore. 
Did you upgrade your pymodaq version by accident or something? :-)   Anyway, for the time being, downgrade your pymodaq and let us know if you still have an error

@seb5g Yes, now that I can reproduce the error I'll try to understand where it comes from - probably next week

**Comment by malik-irain** [comment]
Did you find the time to pinpoint this issue with the Zaber plugin @rgeneaux ?

**Comment by seb5g** [comment]
@rgeneaux  Is the plugin working anew?
