### ISSUE TITLE
No possibility to add comments from the h5browser

### ISSUE THREAD

**Issue by LMSC-NTappy** [PyMoDAQ/PyMoDAQ#94]
Trying to add a comment on any node from the h5browser raises a file not writable error
```
2023-01-16 14:03:56,713 - pymodaq.h5modules - ERROR - the file is not writable
Traceback (most recent call last):
  File "c:\users\user\documents\git\pymodaq\src\pymodaq\daq_utils\h5modules.py", line 1212, in add_comments
    node.attrs['comments'] = comment
  File "c:\users\user\documents\git\pymodaq\src\pymodaq\daq_utils\h5backend.py", line 314, in __setitem__
    set_attr(self._node.node, key, value, backend=self.backend)
  File "c:\users\user\documents\git\pymodaq\src\pymodaq\daq_utils\h5backend.py", line 382, in set_attr
    node._v_attrs[attr_name] = JsonConverter.object2json(attr_value)
  File "C:\Users\user\Miniconda3\envs\pmd_dev\lib\site-packages\tables\attributeset.py", line 563, in __setitem__
    self.__setattr__(name, value)
  File "C:\Users\user\Miniconda3\envs\pmd_dev\lib\site-packages\tables\attributeset.py", line 466, in __setattr__
    nodefile._check_writable()
  File "C:\Users\user\Miniconda3\envs\pmd_dev\lib\site-packages\tables\file.py", line 2167, in _check_writable
    raise FileModeError("the file is not writable")
tables.exceptions.FileModeError: the file is not writable
```
Reason for this is that files are opened read-only in the H5Browser and there is no possibility to change this: 

https://github.com/PyMoDAQ/PyMoDAQ/blob/44992fbedb1b765a8d4dea801c53479676b4e73c/src/pymodaq/daq_utils/h5modules.py#L2223-L2229

We could simply change `r` to `r+` in the last line to fix this.

However it might be a good idea to keep the possibility to decide on this, what do you think? Also, thoughts on v4?

Edit: I verified and changing `r` to `r+` does the trick. Including both backends

**Comment by seb5g** [comment]
well then include it in your pull request, it is a good idea. What do you mean by thoughts on v4?

**Comment by seb5g** [comment]
I just added this modification into v4 branch. I let you add it to v3 pull request
